<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Define a macro for the robot description -->
  <xacro:macro name="robot_description" params="prefix camera_name=zedm camera_model=zedm">

    <!-- Properties -->
    <xacro:if value="${prefix != ''}">
      <xacro:property name="prefix_" value="${prefix}_"/>
    </xacro:if>
    <xacro:if value="${prefix == ''}">
      <xacro:property name="prefix_" value=""/>
    </xacro:if>

    <xacro:property name="wheel_radius" value="0.08" />
    <xacro:property name="base_footprint_z_offset" value="0.0295" />

    <!-- Materials/Colors -->
    <material name="yellow">
      <color rgba="1 1 0 1"/>
    </material>

    <material name="orange">
      <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
      <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="red">
      <color rgba="1 0 0 1"/>
    </material>

    <link name="${prefix_}base_link">
      <inertial>
        <origin
          xyz="0.00180125809402712 0.000803676445247231 0.01518679730351"
          rpy="0 0 0" />
        <mass
          value="0.657677203206575" />
        <inertia
          ixx="0.00086538199329254"
          ixy="-2.9353575955111E-07"
          ixz="2.01709713615107E-05"
          iyy="0.00372020827025877"
          iyz="-4.62454840349382E-06"
          izz="0.00438426362438441" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
            <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_base_link.stl"/>
        </geometry>
        <material name="blue"/>
      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_base_link.stl" />
            <!-- <box size="0.28 0.13 0.08"/> -->
        </geometry>
      </collision>
    </link>

    <!-- Robot Footprint -->
    <link name="${prefix_}base_footprint"/>
    <joint name="${prefix_}base_joint" type="fixed">
      <parent link="${prefix_}base_link"/>
      <child link="${prefix_}base_footprint"/>
      <origin xyz="0.0 0.0 -${wheel_radius + base_footprint_z_offset}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix_}front_left_wheel_link">
      <inertial>
        <origin
          xyz="-2.6737853597858E-10 1.57494023378391E-09 0.00586031499671241"
          rpy="0 0 0" />
        <mass
          value="0.0636859538546401" />
        <inertia
          ixx="0.000148107353320268"
          ixy="-1.35785185033322E-11"
          ixz="4.45745626426646E-12"
          iyy="0.000148107350264006"
          iyz="1.98277930663145E-12"
          izz="0.000285045799220755" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_front_left_wheel.stl" />
        </geometry>
        <material name="orange"/>

      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_front_left_wheel.stl" />
          <!-- <sphere radius="0.08"/> -->
        </geometry>
      </collision>
    </link>
    <joint name="${prefix_}front_left_wheel_joint" type="continuous">
      <origin xyz="0.12851 0.11738 -0.022625" rpy="-1.5708 0 0" />
      <parent link="${prefix_}base_link" />
      <child link="${prefix_}front_left_wheel_link" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix_}front_right_wheel_link">
      <inertial>
        <origin
          xyz="-1.3376E-09 -8.8541E-10 0.0058603"
          rpy="0 0 0" />
        <mass
          value="0.063686" />
        <inertia
          ixx="0.00014811"
          ixy="-5.3705E-12"
          ixz="-3.5018E-12"
          iyy="0.00014811"
          iyz="3.3368E-12"
          izz="0.00028505" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_front_right_wheel.stl" />
        </geometry>
        <material name="orange"/>
      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_front_right_wheel.stl" />
          <!-- <sphere radius="0.08"/> -->
        </geometry>
      </collision>
    </link>
    <joint name="${prefix_}front_right_wheel_joint" type="continuous">
      <origin xyz="0.12051 -0.11682 -0.022625" rpy="1.5708 0 0" />
      <parent link="${prefix_}base_link" />
      <child link="${prefix_}front_right_wheel_link" />
      <axis xyz="0 0 -1" />
    </joint>

    <link name="${prefix_}back_left_wheel_link">
      <inertial>
        <origin
          xyz="-9.53E-10 -1.113E-09 0.0058603"
          rpy="0 0 0" />
        <mass
          value="0.063686" />
        <inertia
          ixx="0.00014811"
          ixy="-4.9708E-12"
          ixz="-4.0149E-12"
          iyy="0.00014811"
          iyz="1.9832E-12"
          izz="0.00028505" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_back_left_wheel.stl" />
        </geometry>
        <material name="orange"/>
      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_back_left_wheel.stl" />
          <!-- <sphere radius="0.08"/> -->
        </geometry>
      </collision>
    </link>
    <joint name="${prefix_}back_left_wheel_joint" type="continuous">
      <origin xyz="-0.11949 0.11738 -0.022625" rpy="-1.5708 0 0" />
      <parent link="${prefix_}base_link" />
      <child link="${prefix_}back_left_wheel_link" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix_}back_right_wheel_link">
      <inertial>
        <origin
          xyz="-3.4938159310105E-10 -6.88384349523119E-11 0.00586031504576194"
          rpy="0 0 0" />
        <mass
          value="0.063685952885413" />
        <inertia
          ixx="0.000148107341904413"
          ixy="-9.56591142331185E-12"
          ixz="-4.24605263320539E-13"
          iyy="0.000148107361436709"
          iyz="9.18578002146026E-13"
          izz="0.000285045798997703" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_back_right_wheel.stl" />
        </geometry>
        <material name="orange"/>
      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_back_right_wheel.stl" />
          <!-- <sphere radius="0.08"/> -->
        </geometry>
      </collision>
    </link>
    <joint name="${prefix_}back_right_wheel_joint" type="continuous">
      <origin xyz="-0.12749 -0.11682 -0.022625" rpy="1.5708 0 0" />
      <parent link="${prefix_}base_link" />
      <child link="${prefix_}back_right_wheel_link" />
      <axis xyz="0 0 -1" />
    </joint>

    <link name="${prefix_}${camera_name}_camera_mount_link">
      <inertial>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <mass
          value="0" />
        <inertia
          ixx="0"
          ixy="0"
          ixz="0"
          iyy="0"
          iyz="0"
          izz="0" />
      </inertial>
      <visual>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_camera_mount.stl" />
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <geometry>
          <mesh
            filename="file://$(find arcs_cohort_description)/meshes/new_camera_mount.stl" />
          <!-- <box size="0.05 0.115 0.05" /> -->
        </geometry>
      </collision>
    </link>
    <joint name="${prefix_}camera_mount_joint" type="fixed">
      <origin xyz="0.14426 0.00028171 0.094535" rpy="0 0 0" />
      <parent link="${prefix_}base_link" />
      <child link="${prefix_}${camera_name}_camera_mount_link" />
      <axis xyz="0 0 0" />
    </joint>

  </xacro:macro>

</robot>
